---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-storage-nfs
  namespace: vaultwarden
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi